<a href="https://colab.research.google.com/github/Ankur099IIT/Aurelion-Geron--Hands-on-ML-with-sklearn-keras-and-tf-book--codes-and-excercises/blob/main/chap_10_California_housing_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [4]:
housing = fetch_california_housing()

In [6]:
type(housing)

sklearn.utils.Bunch

In [10]:
housing

{'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars

In [13]:
housing.data, housing.target

(array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]))

In [14]:
housing.data.shape, housing.target.shape

((20640, 8), (20640,))

In [15]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target) # bydefa

In [18]:
X_train_full.shape, X_test.shape

((15480, 8), (5160, 8))

In [19]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [21]:
X_train.shape, X_valid.shape

((11610, 8), (3870, 8))

In [24]:
X_train[:5]

array([[ 4.73610000e+00,  4.10000000e+01,  5.35207824e+00,
         1.01222494e+00,  1.06300000e+03,  2.59902200e+00,
         3.76600000e+01, -1.22420000e+02],
       [ 5.05700000e+00,  4.60000000e+01,  5.21978022e+00,
         1.03663004e+00,  7.82000000e+02,  2.86446886e+00,
         3.39800000e+01, -1.18360000e+02],
       [ 1.22860000e+00,  2.80000000e+01,  3.08080808e+00,
         9.87373737e-01,  1.28600000e+03,  3.24747475e+00,
         3.27500000e+01, -1.17090000e+02],
       [ 1.83930000e+00,  1.80000000e+01,  2.09042553e+00,
         1.00531915e+00,  4.29000000e+02,  2.28191489e+00,
         3.37500000e+01, -1.18280000e+02],
       [ 2.21320000e+00,  2.20000000e+01,  6.00900901e+00,
         1.17567568e+00,  5.97000000e+02,  2.68918919e+00,
         4.01700000e+01, -1.20940000e+02]])

In [25]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

In [38]:
X_train_scaled[:5], X_test_scaled[:5].shape

(array([[ 0.44457579,  0.98160613, -0.04074146, -0.16162868, -0.32501312,
         -0.06063213,  0.95323764, -1.41723119],
        [ 0.61222689,  1.37626915, -0.08811499, -0.11726073, -0.57208829,
         -0.02449128, -0.77559349,  0.60542868],
        [-1.38788363, -0.04451772, -0.85404229, -0.20680764, -0.12893567,
          0.02765533, -1.3534365 ,  1.23813263],
        [-1.06882932, -0.83384375, -1.20868039, -0.17418326, -0.88247098,
         -0.10380657, -0.88364543,  0.64528405],
        [-0.87348889, -0.51811334,  0.19449358,  0.13552131, -0.73475344,
         -0.04835578,  2.13241321, -0.6799069 ]]), (5, 8))

In [45]:
X_train_scaled[0,:].shape

(8,)

In [46]:
import tensorflow as tf

model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape = X_train_scaled[0,:].shape),
        tf.keras.layers.Dense(30, activation = 'relu'),
        tf.keras.layers.Dense(1)
])

In [47]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                270       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.compile(loss = 'mse',
              optimizer = 'sgd')

In [49]:
history = model.fit(X_train_scaled, y_train, epochs = 20, validation_data = (X_valid_scaled, y_valid))

Epoch 1/20
363/363 [==============================] - 5s 4ms/step - loss: 1.6194 - val_loss: 0.7562
Epoch 2/20
363/363 [==============================] - 1s 4ms/step - loss: 0.5447 - val_loss: 0.4835
Epoch 3/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4173 - val_loss: 0.4136
Epoch 4/20
363/363 [==============================] - 1s 4ms/step - loss: 1.0701 - val_loss: 0.4436
Epoch 5/20
363/363 [==============================] - 2s 4ms/step - loss: 0.5015 - val_loss: 0.4213
Epoch 6/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4026 - val_loss: 0.4075
Epoch 7/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3992 - val_loss: 0.4009
Epoch 8/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4546 - val_loss: 0.4081
Epoch 9/20
363/363 [==============================] - 1s 4ms/step - loss: 1.0627 - val_loss: 0.4252
Epoch 10/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4202 - val_loss: 0.4071

In [52]:
mse_test = model.evaluate(X_test_scaled, y_test)

162/162 [==============================] - 1s 3ms/step - loss: 0.3574


In [53]:
y_preds = model.predict(X_test_scaled[:3])

In [54]:
y_preds

array([[1.8069333],
       [1.5478987],
       [1.0104868]], dtype=float32)